[2025-06-06T21:32:34.723-0300] {processor.py:157} INFO - Started process (PID=51495) to work on /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:32:34.723-0300] {processor.py:826} INFO - Processing file /home/alex/Homeworks/HW3/dags/test.py for tasks to queue
[2025-06-06T21:32:34.724-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:32:34.724-0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:32:34.943-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:32:34.942-0300] {dagbag.py:350} ERROR - Failed to import: /home/alex/Homeworks/HW3/dags/test.py
Traceback (most recent call last):
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alex/Homeworks/HW3/dags/test.py", line 76, in <module>
    tk_load >> transform_data
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 87, in __rshift__
    self.set_downstream(other)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 229, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 181, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'function' object has no attribute 'update_relative'
[2025-06-06T21:32:34.944-0300] {processor.py:838} WARNING - No viable dags retrieved from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:32:35.046-0300] {processor.py:179} INFO - Processing /home/alex/Homeworks/HW3/dags/test.py took 0.325 seconds
[2025-06-06T21:33:05.372-0300] {processor.py:157} INFO - Started process (PID=51512) to work on /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:33:05.399-0300] {processor.py:826} INFO - Processing file /home/alex/Homeworks/HW3/dags/test.py for tasks to queue
[2025-06-06T21:33:05.401-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:33:05.400-0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:33:05.591-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:33:05.590-0300] {dagbag.py:350} ERROR - Failed to import: /home/alex/Homeworks/HW3/dags/test.py
Traceback (most recent call last):
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alex/Homeworks/HW3/dags/test.py", line 76, in <module>
    tk_load >> transform_data
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 87, in __rshift__
    self.set_downstream(other)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 229, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 181, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'function' object has no attribute 'update_relative'
[2025-06-06T21:33:05.591-0300] {processor.py:838} WARNING - No viable dags retrieved from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:33:05.686-0300] {processor.py:179} INFO - Processing /home/alex/Homeworks/HW3/dags/test.py took 0.316 seconds
[2025-06-06T21:33:39.015-0300] {processor.py:157} INFO - Started process (PID=51594) to work on /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:33:39.039-0300] {processor.py:826} INFO - Processing file /home/alex/Homeworks/HW3/dags/test.py for tasks to queue
[2025-06-06T21:33:39.041-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:33:39.040-0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:33:39.253-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:33:39.251-0300] {dagbag.py:350} ERROR - Failed to import: /home/alex/Homeworks/HW3/dags/test.py
Traceback (most recent call last):
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alex/Homeworks/HW3/dags/test.py", line 76, in <module>
    tk_load >> transform_data
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 87, in __rshift__
    self.set_downstream(other)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 229, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 181, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'function' object has no attribute 'update_relative'
[2025-06-06T21:33:39.253-0300] {processor.py:838} WARNING - No viable dags retrieved from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:33:39.368-0300] {processor.py:179} INFO - Processing /home/alex/Homeworks/HW3/dags/test.py took 0.355 seconds
[2025-06-06T21:34:10.446-0300] {processor.py:157} INFO - Started process (PID=51609) to work on /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:10.467-0300] {processor.py:826} INFO - Processing file /home/alex/Homeworks/HW3/dags/test.py for tasks to queue
[2025-06-06T21:34:10.469-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:10.469-0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:10.688-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:10.687-0300] {dagbag.py:350} ERROR - Failed to import: /home/alex/Homeworks/HW3/dags/test.py
Traceback (most recent call last):
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alex/Homeworks/HW3/dags/test.py", line 76, in <module>
    tk_load >> transform_data
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 87, in __rshift__
    self.set_downstream(other)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 229, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 181, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'function' object has no attribute 'update_relative'
[2025-06-06T21:34:10.689-0300] {processor.py:838} WARNING - No viable dags retrieved from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:10.791-0300] {processor.py:179} INFO - Processing /home/alex/Homeworks/HW3/dags/test.py took 0.348 seconds
[2025-06-06T21:34:29.955-0300] {processor.py:157} INFO - Started process (PID=51728) to work on /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:29.974-0300] {processor.py:826} INFO - Processing file /home/alex/Homeworks/HW3/dags/test.py for tasks to queue
[2025-06-06T21:34:29.976-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:29.975-0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:30.222-0300] {processor.py:836} INFO - DAG(s) dict_keys(['test1']) retrieved from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:30.459-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:30.459-0300] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-06T21:34:30.468-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:30.468-0300] {dag.py:3504} INFO - Setting next_dagrun for test1 to 2025-06-06T02:28:40.519682+00:00, run_after=2025-06-07T02:28:40.519682+00:00
[2025-06-06T21:34:30.798-0300] {processor.py:179} INFO - Processing /home/alex/Homeworks/HW3/dags/test.py took 0.844 seconds
[2025-06-06T21:34:52.364-0300] {processor.py:157} INFO - Started process (PID=51787) to work on /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:52.380-0300] {processor.py:826} INFO - Processing file /home/alex/Homeworks/HW3/dags/test.py for tasks to queue
[2025-06-06T21:34:52.382-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:52.382-0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:52.650-0300] {processor.py:836} INFO - DAG(s) dict_keys(['taxi_pipeline']) retrieved from /home/alex/Homeworks/HW3/dags/test.py
[2025-06-06T21:34:52.926-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:52.925-0300] {manager.py:504} INFO - Created Permission View: can edit on DAG:taxi_pipeline
[2025-06-06T21:34:53.174-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:53.173-0300] {manager.py:504} INFO - Created Permission View: can delete on DAG:taxi_pipeline
[2025-06-06T21:34:53.274-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:53.273-0300] {manager.py:504} INFO - Created Permission View: can read on DAG:taxi_pipeline
[2025-06-06T21:34:53.294-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:53.293-0300] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-06T21:34:53.298-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:53.298-0300] {dag.py:2763} INFO - Creating ORM DAG for taxi_pipeline
[2025-06-06T21:34:53.303-0300] {logging_mixin.py:150} INFO - [2025-06-06T21:34:53.303-0300] {dag.py:3504} INFO - Setting next_dagrun for taxi_pipeline to 2025-06-06T00:34:53.303328+00:00, run_after=2025-06-07T00:34:53.303328+00:00
[2025-06-06T21:34:53.444-0300] {processor.py:179} INFO - Processing /home/alex/Homeworks/HW3/dags/test.py took 1.082 seconds
